# -*- coding: utf-8 -*-
"""Introdução a Data Science

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wpSjqGTcIzMslOwP2oo5dE-yZgRqh2D2

#Comando para mudar a versão da biblioteca importada(Restart runTime)
"""

#!pip install seaborn==0.9.0

#import seaborn as sns
#print(sns.__version__)

"""#***AULA 1:***

# Analisando as notas - geral
"""

import pandas as pd

notas = pd.read_csv("ratings.csv")
notas.head()

notas.shape

notas.columns = ["usiarioId", "filmeId", "nota", "Momento"]
notas.head()

notas.shape

notas

notas['nota']

print(sorted(notas))

notas['nota'].value_counts()

notas['nota'].mean()

notas.nota

notas.nota.plot()

notas.nota.head()

notas.nota.plot()

notas.nota.plot(kind='hist')

notas.nota.median()

print(notas.nota.mean())
print(notas.nota.median())

print("Média= ", notas.nota.mean())
print("Mediana= ", notas.nota.median())

notas.nota.describe()

import seaborn as sns

sns.boxplot(notas.nota)

notas['nota'].unique()
notas['nota'].value_counts()

print("Media",notas.nota.mean())
print("Mediana",notas.nota.median())

"""#***AULA 2:***

# Olhando o filmes
"""

filmes = pd.read_csv("movies.csv")
filmes.columns = ["filmeId", "titulo", "generos"]
filmes.head()

notas.head()

notas.query("filmeId==1")

notas.query("filmeId==1").nota

"""# Analisando algumas notas especificas, por filme"""

notas.query("filmeId==1").nota.mean()

notas.query("filmeId==2").nota.mean()

notas.groupby("filmeId")

notas.groupby("filmeId").mean()

medias_por_filme = notas.groupby("filmeId").mean()["nota"]
medias_por_filme.head()

medias_por_filme.plot(kind="hist")

import matplotlib.pyplot as plt

plt.figure(figsize= (5,8))
sns.boxplot(y=medias_por_filme)

medias_por_filme.describe()

"""##O metodo seaborn.distplot foi descontinuado, está obsoleto,  substituir por [displot()](https://seaborn.pydata.org/generated/seaborn.displot.html) ou [histplot() ](https://seaborn.pydata.org/generated/seaborn.histplot.html#seaborn.histplot)

###Tomar cuidado com o uso do "bins"
"""

sns.distplot(medias_por_filme, bins=10)

sns.histplot(medias_por_filme, kde=True)

import matplotlib.pyplot as plt

plt.hist(medias_por_filme)
plt.title("Histograma das médias dos filmes")

"""#***AULA 3:***"""

tmdb = pd.read_csv("tmdb_5000_movies.csv")
tmdb.head()

tmdb.original_language.unique() # categorica nominal

# primeiro grau
# segundo grau
# terceiro grau
# 1 grau < 2 grau < 3 grau => categorica ordinal

# budget => orcamento => quantitativa continuo

# quantidade de votos => 1, 2, 3, 4, nao existe 2.5 votos
# notas do movielens => 0.5, 1, 1.5, 2, ..., 5, não existe 2.7

"""#***AULA 4: ***

###Analisando tipo de variaveis que são categoricas mas não tem uma ordem "natural"
"""

tmdb.original_language.value_counts().index

tmdb.original_language.value_counts().values

tmdb.original_language.value_counts()

tmdb.original_language.value_counts().to_frame()

contagem_de_lingua = tmdb.original_language.value_counts().to_frame().reset_index()
contagem_de_lingua.columns = ["original_language", "total"]
contagem_de_lingua.head()

sns.barplot(x = "original_language", y = "total", data = contagem_de_lingua)

sns.catplot(x = "original_language", kind="count", data = tmdb)

"""#***AULA 4.1:***"""

plt.pie(contagem_de_lingua["total"], labels =contagem_de_lingua["original_language"])

total_por_lingua = tmdb["original_language"].value_counts()
total_geral = total_por_lingua.sum()
total_de_ingles = total_por_lingua.loc["en"]
total_do_resto = total_geral - total_de_ingles
print(total_de_ingles, total_do_resto)

dados = {
    'lingua': ['ingles', 'outros'],
    'total' : [total_de_ingles, total_do_resto]
}
dados = pd.DataFrame(dados)
dados

sns.barplot(x="lingua", y= "total", data= dados)

"""#***AULA 4.2:***"""

plt.pie(dados["total"], labels = dados["lingua"])

total_por_lingua_de_outros_filmes = tmdb.query("original_language != 'en'").original_language.value_counts()
total_por_lingua_de_outros_filmes

"""#***AULA 5:***"""

filmes_sem_lingua_original_em_ingles = tmdb.query("original_language != 'en'")

sns.catplot(x = "original_language", kind="count", data = filmes_sem_lingua_original_em_ingles)

sns.catplot(x = "original_language", kind="count", data = filmes_sem_lingua_original_em_ingles,
            aspect= 2,
            palette= "GnBu_d",
            order= total_por_lingua_de_outros_filmes.index)

"""###Exemplo de gráfico linear"""

import seaborn as sns
sns.set(style="ticks")

# Load the example dataset for Anscombe's quartet
df = sns.load_dataset("anscombe")

# Show the results of a linear regression within each dataset
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=df,
           col_wrap=2, ci=None, palette="muted", height=4,
           scatter_kws={"s": 50, "alpha": 1})

"""#***AULA 6:***

#Revisando o papel da média, mediana, medidas de tendência central, dispersão, desvio padrão, box plot, histograma
"""

filmes.head(2)

notas_do_toy_story = notas.query("filmeId==1")
notas_do_jumanji = notas.query("filmeId==2")
print(len(notas_do_toy_story), len(notas_do_jumanji))

print("Nota média do Toy Story %.2f" % notas_do_toy_story.nota.mean())
print("Nota média do Jumanji %.2f" % notas_do_jumanji.nota.mean())

print(notas_do_toy_story.nota.std(), notas_do_jumanji.nota.std())

print("Nota mediana do Toy Story %.2f" % notas_do_toy_story.nota.median())
print("Nota mediana do Jumanji %.2f" % notas_do_jumanji.nota.median())

import numpy as np

filme1 = np.append(np.array([2.5] * 10), np.array([3.5] * 10))
filme2 = np.append(np.array([5] * 10), np.array([1] * 10))

print(filme1.mean(), filme2.mean())
print(np.std(filme1), np.std(filme2))
print(np.median(filme1), np.median(filme2))

plt.hist(filme1)
plt.hist(filme2)

plt.boxplot([filme1, filme2])

plt.boxplot([notas_do_toy_story.nota, notas_do_jumanji.nota])

sns.boxplot(x = "filmeId", y = "nota", data = notas.query("filmeId in [1,2,3,4,5]"))